# Site settings
title: Lochness
email: lochness@omniti.com
url: http://mistifyio.com/lochness
description: "Simple Cloud Management"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: A0A0A0 #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: CF0000 #A2122F
  
# Footer settings
footer:
  copyright: OmniTI
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/mistifyio
  - title: github
    url: http://github.com/mistifyio

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210
  
# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
